trigger:
  - main # Ajusta la rama según tus necesidades

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: BuildAndTest
    displayName: "Build and Test"
    steps:
      - checkout: self

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8" # Ajusta la versión de Python según tus necesidades
          addToPath: true
