name: Python CI

on:
  push:
    branches:
      - main # Ajusta la rama según tus necesidades

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Puedes ajustar la versión de Python según tus necesidades

